/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Snakez;

import java.util.List;

/**
 *
 * @author Alumno
 */
public class Puntuaciones extends javax.swing.JFrame {
 public DbManager manejadorConfig = new DbManager();
    /**
     * Creates new form Puntuaciones
     */
    public Puntuaciones() {
        initComponents();
        cargarPuntuaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();
        lblP3 = new javax.swing.JLabel();
        lblP4 = new javax.swing.JLabel();
        lblP5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Mejores Puntuaciones");

        lbl1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl1.setText("jLabel2");

        lbl2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl2.setText("jLabel2");

        lbl3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl3.setText("jLabel2");

        lbl4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl4.setText("jLabel2");

        lbl5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl5.setText("jLabel2");

        lblP1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblP1.setText("jLabel2");

        lblP2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblP2.setText("jLabel2");

        lblP3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblP3.setText("jLabel2");

        lblP4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblP4.setText("jLabel2");

        lblP5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblP5.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("Puntuacion");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl5)
                    .addComponent(lbl4)
                    .addComponent(lbl3)
                    .addComponent(lbl2)
                    .addComponent(lbl1)
                    .addComponent(jLabel2))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblP5)
                    .addComponent(lblP4)
                    .addComponent(lblP3)
                    .addComponent(lblP2)
                    .addComponent(lblP1)
                    .addComponent(jLabel3)))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1)
                    .addComponent(lblP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP2)
                    .addComponent(lbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP3)
                    .addComponent(lbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP4)
                    .addComponent(lbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP5)
                    .addComponent(lbl5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarPuntuaciones(){
        List<List> esto = manejadorConfig.selectPuntuaciones();
        List<String> nombres = esto.get(0);
        List<Integer> puntuaciones = esto.get(1);

            lbl1.setText(nombres.get(0));
            lblP1.setText(String.valueOf(puntuaciones.get(0)));
        lbl2.setText(nombres.get(1));
            lblP2.setText(String.valueOf(puntuaciones.get(1)));
            lbl3.setText(nombres.get(2));
            lblP3.setText(String.valueOf(puntuaciones.get(2)));
            lbl4.setText(nombres.get(3));
            lblP4.setText(String.valueOf(puntuaciones.get(3)));
            lbl5.setText(nombres.get(4));
            lblP5.setText(String.valueOf(puntuaciones.get(4)));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP3;
    private javax.swing.JLabel lblP4;
    private javax.swing.JLabel lblP5;
    // End of variables declaration//GEN-END:variables
}
